### ISSUE TITLE
 请问一下，这个组件支持默认图片这个功能吗？

### ISSUE THREAD

**Issue by jamessawyer** [zcgit/rn-img-cache#1]
我想在图片请求到之前添加一个占位图片，请问这个组件支持这个功能吗？

**Comment by zcgit** [comment]
可以的，RN自带的 <b>Image</b> 本身就有 <b>defaultSource</b> 这个属性的，不过那个的体验比较生硬，比如你网络图片下的比较快，那么可能会出现闪一下的感觉，如果是个列表，那么就更难看了，如果你想提升体验，可以在图片下载完成后显示的时候做一个渐入的效果，这样会更平和点，我准备把这个也加入到这个库里:)

**Comment by jamessawyer** [comment]
期待这个功能，LOL

**Comment by jamessawyer** [comment]
好的 感谢

**Comment by jamessawyer** [comment]
@zcgit  请问一下,如果后台将图片换了，但是返回的url没有变，这边图片没有更新，还是使用旧的图片，该怎么处理？

**Comment by zcgit** [comment]
> 该怎么处理

你这种一般情况下是不允许后台这样换图片的，后台必须保证图片名称唯一性，不能在没改变图片名称的前提下更换图片。<br>
如果确实遇到了你这种情况，那可以把这个图片不放到缓存里就行了，每次都从网络拉取最新的，或者只在本次应用打开的周期内缓存，下次打开应用的时候还是需要重新下载。

**Comment by jamessawyer** [comment]
哦哦 我试了一下用原生的Image组件，然后从1.0.0升级到1.0.1，发现测试机中有一台还是使用旧的图片，都开始怀疑人生了。。。还是要在图片后面加上时间戳是个解决办法。
再向大佬请求一个问题，A页面我使用了默认的占位图，等图片a下载完成之后正常显示，我进入B页面，这个页面也会去请求图片b，在b图片请求完成之前，我点击该页面的b图片，希望在A页面中显示b图片，但是因为b图片没有请求完成的原因，现在A页面中还是显示的a图片，我希望如果B页面没有请求完成 则A页面中重新显示占位图，而不是旧的a图片，这样会造成不同步
不知道这样表述能不能理解，感谢！

**Comment by zcgit** [comment]
> 中重新显示占位图

- 你的需求是不是我给你一个图片是否下载完成的回调给你就行了？然后你自己根据回调去做逻辑判断。<br>
- 我理解你的需求简单点描述就是我在B页面想修改A页面的元素，如果B页面的图片已下载完成，则让A页面的元素也换成B刚下载的图片，否则，让A页面的元素再设置成占位图，我理解没错吧。

**Comment by jamessawyer** [comment]
嗯 是的 现在我不知道怎么去判断这个图片是否已经下载完成了，后台返回的就是一个url，我在想怎么url对应的图片什么时候下载好了 我这边有办法获取得到吗？

**Comment by zcgit** [comment]
> 嗯 是的 现在我不知道怎么去判断这个图片是否已经下载完成了，后台返回的就是一个url，我在想怎么url对应的图片什么时候下载好了 我这边有办法获取得到吗？

好的，我明白了你的需求了，我准备加一个回调 :)

**Comment by zcgit** [comment]
> > 嗯 是的 现在我不知道怎么去判断这个图片是否已经下载完成了，后台返回的就是一个url，我在想怎么url对应的图片什么时候下载好了 我这边有办法获取得到吗？
> 
> 好的，我明白了你的需求了，我准备加一个回调 :)
@jamessawyer done!

**Comment by jamessawyer** [comment]
好的 真的厉害 lol 十分感谢 我先研究一下怎么使用

**Comment by jamessawyer** [comment]
@zcgit 今天将项目中的组件替换成这个组件了 发现了几个问题
  1.使用onLoadEnded 回调返回的结果并没有生效，图片已经下载完成 但是回调显示是否下载成功为false
  2.如果下载失败 defaultSource占位图不会显示😂

**Comment by zcgit** [comment]
@jamessawyer 收到，我再查查看。
